version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: parasocial-db
    environment:
      POSTGRES_DB: parasocial
      POSTGRES_USER: parasocial_user
      POSTGRES_PASSWORD: parasocial_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: